# Generated by Django 4.1.7 on 2023-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacts_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=122, null=True)),
                ('Phone', models.CharField(blank=True, max_length=122, null=True)),
                ('Email', models.CharField(blank=True, max_length=122, null=True)),
                ('desc', models.TextField(blank=True, max_length=1221, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
