# Generated by Django 4.1.7 on 2023-03-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
